services:
  traefik:
    image: "traefik:v3.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=me@fredpena.dev"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: traefik/whoami
    command:
      # It tells whoami to start listening on 2001 instead of 80
      - --port=2001
      - --name=iamfoo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fredpena-b.rule=Host(`balancer.fredpena.dev`)"
      - "traefik.http.routers.fredpena-b.service=fredpena-b-service"
      - "traefik.http.routers.fredpena-b.entrypoints=websecure"
      - "traefik.http.services.fredpena-b-service.loadbalancer.server.port=2001"
      - "traefik.http.routers.fredpena-b.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.onlyhttps.redirectscheme.scheme=https"
      - "traefik.http.middlewares.onlyhttps.redirectscheme.permanent=true"

  ssdwa:
    image: fredpena/ssdwa:1.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fredpena.rule=Host(`app.fredpena.dev`)"
      - "traefik.http.routers.fredpena.service=fredpena-service"
      - "traefik.http.routers.fredpena.entrypoints=websecure"
      - "traefik.http.services.fredpena-service.loadbalancer.server.port=37650"
      - "traefik.http.routers.fredpena.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.onlyhttps.redirectscheme.scheme=https"
      - "traefik.http.middlewares.onlyhttps.redirectscheme.permanent=true"